export App from './App/App';
export Home from './Home/Home';
export ZipAdd from './Zip/Add';
export ZipList from './Zip/List';
export ZipDetail from './Zip/Detail';
export ZipUpdata from './Zip/Updata';
export Login from './Login/Login';
export Register from './Register/Register';
export NotFound from './NotFound/NotFound';
